[workspace]
members = [
    "tunnel-server",
    "tunnel-client"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "Simple TCP tunnel for HTTP traffic"
license = "MIT" 